// import FileUploadInline from './store/modules/plugins/inlineFileUpload.js'

import {
	InlineEditor,
	Alignment,
	Autoformat,
	AutoImage,
	Autosave,
	Base64UploadAdapter,
	BlockQuote,
	Bold,
	CloudServices,
	Emoji,
	Essentials,
	Heading,
	ImageBlock,
	ImageCaption,
	ImageInline,
	ImageInsert,
	ImageInsertViaUrl,
	ImageResize,
	ImageStyle,
	ImageTextAlternative,
	ImageToolbar,
	ImageUpload,
	Indent,
	IndentBlock,
	Italic,
	Link,
	LinkImage,
	List,
	ListProperties,
	MediaEmbed,
	Mention,
	Paragraph,
	PasteFromOffice,
	Table,
	TableCaption,
	TableCellProperties,
	TableColumnResize,
	TableProperties,
	TableToolbar,
	TextTransformation,
	TodoList,
	Underline
} from 'ckeditor5';

import 'ckeditor5/ckeditor5.css';

export default [

    Alignment,
		Autoformat,
		//AutoImage,
		//Autosave,
		//Base64UploadAdapter,
		BlockQuote,
		Bold,
		//CloudServices,
		//Emoji,
		Essentials,
		Heading,
		//ImageBlock,
		//ImageCaption,
		//ImageInline,
		//ImageInsert,
		//ImageInsertViaUrl,
		//ImageResize,
		//ImageStyle,
		//ImageTextAlternative,
		//ImageToolbar,
		//ImageUpload,
		//Indent,
		//IndentBlock,
		Italic,
		Link,
		//LinkImage,
		List,
		//ListProperties,
		//MediaEmbed,
		//Mention,
		Paragraph,
		//PasteFromOffice,
		Table,
		//TableCaption,
		//TableCellProperties,
		TableColumnResize,
		//TableProperties,
		TableToolbar,
		TextTransformation,
		//TodoList,
		//Underline

    // FileUploadInline,
]
